### ISSUE TITLE
Question about how to contribute 

### ISSUE THREAD

**Issue by lucienbill** [i365dev/LetterDrop#1]
Hi,

The "how to contribute" section seems to mainly focus on GPT prompts customisation. Is this project open to code modifications made by humans?

For example: if I submit a PR that touches the code directly, would it be accepted or rejected?

Thanks, and good job explaining the "why" and "how" of this repo 👍

**Comment by madawei2699** [comment]
Sorry for this confused note, Obviously AI is only an aid to generating code. This project certainly accepts manual PR. The reason why I used AI to generate the code was because of efficiency considerations, and although I spent ten hours live streaming this project with AI. It seems slower, but I think this is a direction for the future, and generating small to medium-sized projects with AI is completely feasible, and this project is an experimental one based on that. And because it is an MIT license, how to use are no restrictions, you can use AI to modify the code, and you can also modify the code yourself.

**Comment by lucienbill** [comment]
Thanks! The new version of the Readme is clear enough for me, I'm closing the issue 👍
